### PR TITLE
Removed migration duplicate from ChatifyServiceProvider.php causing migration errors

### PR DESCRIPTION
**Pull request by LyndonMcjohnson**

### CODE REVIEW

**Comment by jelleroorda** [comment]
Hey @LyndonMcjohnson, this is the wrong part you're deleting. The part that's supposed to be removed is [this line](https://github.com/munafio/chatify/blob/master/src/ChatifyServiceProvider.php#L33).

**Comment by LyndonMcjohnson** [comment]
Whoa! my bad.
Fixed it.
But deleting those lines also solved the error for me.

**Comment by LyndonMcjohnson** [comment]
Whoa! my bad.
Fixed it.
But deleting those lines also solved the error for me. Thanks again.

**Comment by munafio** [comment]
This issue already been fixed but delayed to be pushed! now it is available with v1.3.4.
Thank you.

**Comment by LyndonMcjohnson** [comment]
Thanks!

**Pull request closed without merging**
