### PR TITLE
I added a sanitizeInput function to prevent xss when sending message

### PR DESCRIPTION
**Pull request by profissionalsid**
When a message is sent and the js appends it, it is possible to send some html and js code, which is interpreted in the browser, and can send some malicious code. This implementation prevents this.

After the message is processed, it is cleaned, but not in the js part.

To reproduce, send:

<h1>Hello</h1>: This is replaced by sanitizing, but you can see it appearing briefly.

<script>alert('hello')</script>: This awaits user interaction.

### CODE REVIEW

**Comment by munafio** [comment]
Hi @profissionalsid ,
Thank you for your notice about this critical issue. But we have two issues as I can see:
First one, DOM manipulation is slower than direct string replacement.
Second, this solution or `sanitizeInput` method creates unnecessary DOM elements, actually we can solve this by storing the inner html then remove the element.

we can do it in a better way like:
```js
function sanitizeInput(inputValue) {
  if (typeof inputValue !== 'string') {
    return '';
  }
  
  if (!/^[a-zA-Z0-9\s\-_]+$/.test(input)) {
    throw new Error('Invalid characters detected'); // or alert
  }
  
  return inputValue
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
```

I think this will cover most cases and much faster than before, no DOM manipulations ..etc

You can try out this one and test that also in your machine locally, then make a changes to this PR.

**Comment by profissionalsid** [comment]
Tested and all good

**Comment by munafio** [comment]
@profissionalsid Thanks for your contribution

**Comment by profissionalsid** [comment]
> @profissionalsid Thanks for your contribution

Today I went to use it, and I realized that because it was delayed, when sending the normal message it becomes undefined and then it is replaced, I apologize for this oversight.

**Pull request merged**
