### PR TITLE
Fix: MassageController not applies changes

### PR DESCRIPTION
**Pull request by rigonlucas**
Here is a question: [https://github.com/munafio/chatify/issues/10](url)
I test the modifications and work fine.
You can test it in a new project and a project to update

Congragulatio for the project
I hope I contributed to the project.

### CODE REVIEW

**Comment by rigonlucas** [comment]
@munafio i can't see any comments in my commits, is everything clean here. 
If you can, send me the link.

**Review by munafio — APPROVED** [review]
Great :) .. but I have some notes to your PR:
* Here in **src/ChatifyServiceProvider.php** there is no need for the default namespace, because you already added that at **config/chatify.php**, so it will be like : 
`'namespace' =>  config('chatify.namespace'),`

* Second, can you change **config/chatify.php** to the following : 
```
/*
    |--------------------------------------------------------------------------
    | Route's controllers namespace
    |--------------------------------------------------------------------------
    |
    | You may need to change the namespace of the route's controllers of 
    | this package after publishing the 'controllers' asset, from the 
    | default one to your App's controllers namespace.
    |
    | By default: Chatify\Http\Controllers
    |
    */
    'namespace' => env('CHATIFY_ROUTES_NAMESPACE', 'Chatify\Http\Controllers'),
```

and thanks a lot to your contribution.

**Comment by rigonlucas** [comment]
Perfect!!!
Remember to set in README.md that config/chatify.php is change... Because projects in production gonna broken.
Because this possibilite i set **'namespace' =>  config('chatify.namespace', 'Chatify\Http\Controllers'),** with a default controller folder in **src/ChatifyServiceProvider.php** when run composer update, the default env was not defined, needing add namespace in config.
I send mi new commit.

I did like so much contribute with your project

Hug

**Comment by rigonlucas** [comment]
*My new commit :smile:

**Review by munafio — APPROVED** [review]
Thanks a lot for your contribution <3
The docs will be updated too.

**Pull request merged**
