### PR TITLE
Request Manipulation in Activity Status

### PR DESCRIPTION
**Pull request by a7md**
The issue :
When changing the activity status it is making a request, and that request contains the user_id of the user. you can just basically edit the user_id to any other user_id and it'll update the status for any user without validation.

The Solution:
Just Changed the method from getting the user_id form the request into getting it from the current logged in user id.

### CODE REVIEW

**Comment by vicenterusso** [comment]
It won't work for leaving status. The logged user might be online forever in that case

**Comment by a7md** [comment]
> It won't work for leaving status. The logged user might be online forever in that case

The issue we had is that some users mess with other users activity via the id, so i think the best alternative to do, is a command to clear unactive user status. or a cron job, or maybe the timestamp of the status active, so if the last online_time was more than 15 minutes, it'll considered an offline user automatically.

 but users updates other users status for me seems to be an issue as they can make a mess.

**Comment by vicenterusso** [comment]
> > It won't work for leaving status. The logged user might be online forever in that case
> 
> The issue we had is that some users mess with other users activity via the id, so i think the best alternative to do, is a command to clear unactive user status. or a cron job, or maybe the timestamp of the status active, so if the last online_time was more than 15 minutes, it'll considered an offline user automatically.
> 
> but users updates other users status for me seems to be an issue as they can make a mess.

Yes thats correct. It's the same solution I did on my own project

**Comment by munafio** [comment]
@a7md That's correct, there should be a validation layer on the request or just as you did .. the one logged in can set their active status only.
But your changes applies only on the API controller as I can see, can you make the changes on the main controller too? if yes, there should be also a changes on the client side code (code.js).

Well done Ahmed, Thanks.

**Comment by munafio** [comment]
@a7md Please let me know if you'll make the changes, to add your changes with the next coming release.

**Comment by a7md** [comment]
> @a7md Please let me know if you'll make the changes, to add your changes with the next coming release.

Sorry for the late replay, I would be more than happy to do them.

- Update the both controllers
- Update The JavaScript File

**Comment by munafio** [comment]
@a7md Thank you Ahmed, I will be waiting your changes to add them to the next coming release v1.6.0 that I'm almost done from it .. but make sure to not broke the functionality on the main controller with the client code.

**Comment by a7md** [comment]
> @a7md Thank you Ahmed, I will be waiting your changes to add them to the next coming release v1.6.0 that I'm almost done from it .. but make sure to not broke the functionality on the main controller with the client code.

I'll close this PR, and push a new one.

**Pull request closed without merging**
