### PR TITLE
Add select to idFetchData Function 

### PR DESCRIPTION
**Pull request by a7md**
Hello,

When i was debugging the network requests, i noticed that idFetchData Function is returning all the user data, which is totally unsecure, as it'll return the user email, etc. and it may return some sensitive data like email, phone number, etc. ( if you are storing them ). and any one can see the response.

### CODE REVIEW

**Comment by a7md** [comment]
@munafio , this is really cool repo and time saver. great job.

**Comment by munafio** [comment]
@a7md Hi Ahmed,
user data returned may used to display them on user's info section at the client side and other places.. but if you want to select specific columns to be returned, then just publish the controller and make your changes as you want. 
So, I think it is not necessary for this PR.

Thanks for your efforts and time.

**Comment by a7md** [comment]
@munafio 
Well, it is up to you.

but in my situation it needed to be hidden as people can see other people email, phone numbers, api tokens, balances. so i think the id, name, avatar, is more than enough. 

and if anyone would like to customize it would be really easy for him. as then he will publish the controller and modify it.
but in general, i think it is better to have select and limit the response fields, as many people will just install it and run it, without understanding the risk of it.

Thanks for your quick reply.

**Comment by munafio** [comment]
@a7md fare enough, I will check the code changed and merge your PR later .. thanks again for your explanation and your time.

**Comment by munafio** [comment]
> 

I'll close this PR, because there are many user props need to be there not just what you've selected and as I mentioned above if anything you see that need to be change, you can easily do that without this PR.

**Pull request closed without merging**
