### PR TITLE
support beyondcode/laravel-websockets

### PR DESCRIPTION
**Pull request by rifrocket**
while using beyondcode/laravel-websockets

``` env

PUSHER_APP_ID=pusher_app_id                               #any random string
PUSHER_APP_KEY=pusher_app_key                          #any random string
PUSHER_APP_SECRET=pusher_app_secret               #any random string
PUSHER_HOST=127.0.0.1                                           
PUSHER_PORT=6001
PUSHER_SCHEME=http                                                #if want to use SSL use `https` instead of `http`
PUSHER_APP_CLUSTER=mt1
LARAVEL_WEBSOCKETS_PORT="${PUSHER_APP_PORT}"

LARAVEL_WEBSOCKETS_SSL_LOCAL_PK=private_key_path #optional if you want to use ssl
LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT=certificate_path #optional if you want to use ssl

```
For more information: https://beyondco.de/docs/laravel-websockets/getting-started/installation

### CODE REVIEW

**Comment by munafio** [comment]
@rifrocket That's the whole thing to get it working? I did not test it yet so I'll make tests on your changes then will notify you with the updates.

**Comment by rifrocket** [comment]
Yes, with these changes the project will simply work with the Laravel web-socket.

I already tested it out with the following  scenarios 

1-without SSL/TLS certificate
2-with SSL/TLS certificate 
3-with official PUSHER service 

I also provided the environment variables for better clarification.

**Comment by munafio** [comment]
@rifrocket you did a great job, in the next days I'll release an update also the documentation to support this feature because it is required by many users .. thank you for your contribution.

**Comment by rifrocket** [comment]
@munafio thanx brother.

**Comment by munafio** [comment]
@rifrocket your contribution now been [released](https://github.com/munafio/chatify/blob/master/CHANGELOG.md#v162-2023-07-27) and also the documentation has a new section for [custom WS server.](https://chatify.munafio.com/custom-websocket-server)

**Comment by rifrocket** [comment]
@munafio thank you so much, i am looking foreword for more contribution in this repository.

**Comment by sahilxjain** [comment]
@munafio Does this also works with Soketi web server ?

**Pull request merged**
